import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1783866736237 implements MigrationInterface {
    name = 'InitialSchema1783866736237'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`tenants\` (\`id\` uuid NOT NULL, \`code\` varchar(255) NOT NULL, \`name\` varchar(255) NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`logo_path\` varchar(255) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_3021c18db2b363ae9324c826c5\` (\`code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` uuid NOT NULL, \`tenant_id\` uuid NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`email\` varchar(255) NOT NULL, \`password_hash\` varchar(255) NOT NULL, \`full_name\` varchar(255) NOT NULL, \`role\` varchar(255) NOT NULL DEFAULT 'technician', \`phone\` varchar(255) NULL, \`city\` varchar(255) NULL, \`country\` varchar(255) NOT NULL DEFAULT 'VN', \`is_remote\` tinyint NOT NULL DEFAULT 0, \`skills\` json NULL, \`is_available\` tinyint NOT NULL DEFAULT 1, \`rating\` decimal(3,2) NOT NULL DEFAULT '5.00', \`is_active\` tinyint NOT NULL DEFAULT 1, UNIQUE INDEX \`IDX_e9f4c2efab52114c4e99e28efb\` (\`tenant_id\`, \`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`customers\` (\`id\` uuid NOT NULL, \`tenant_id\` uuid NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`full_name\` varchar(255) NOT NULL, \`phone\` varchar(255) NOT NULL, \`email\` varchar(255) NULL, \`address\` text NULL, \`city\` varchar(255) NULL, \`country\` varchar(255) NOT NULL DEFAULT 'VN', \`notes\` text NULL, \`customer_score\` decimal(5,2) NOT NULL DEFAULT '0.00', UNIQUE INDEX \`IDX_d9ef0802e47c0384f5831b5973\` (\`tenant_id\`, \`phone\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tickets\` (\`id\` uuid NOT NULL, \`tenant_id\` uuid NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`ticket_code\` varchar(255) NOT NULL, \`customer_id\` uuid NOT NULL, \`assigned_technician_id\` uuid NULL, \`issue_description\` text NOT NULL, \`device_type\` varchar(255) NULL, \`device_model\` varchar(255) NULL, \`status\` varchar(255) NOT NULL DEFAULT 'received', \`priority\` varchar(255) NOT NULL DEFAULT 'normal', \`skill_required\` json NULL, \`quoted_price\` decimal(12,2) NULL, \`final_price\` decimal(12,2) NULL, \`sla_due_at\` datetime NULL, \`closed_at\` datetime NULL, UNIQUE INDEX \`IDX_d83f5fcb42383c9feea08bbe1f\` (\`tenant_id\`, \`ticket_code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ticket_status_history\` (\`id\` uuid NOT NULL, \`tenant_id\` uuid NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`ticket_id\` uuid NOT NULL, \`from_status\` varchar(255) NULL, \`to_status\` varchar(255) NOT NULL, \`changed_by\` uuid NULL, \`note\` text NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ticket_attachments\` (\`id\` uuid NOT NULL, \`tenant_id\` uuid NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`ticket_id\` uuid NOT NULL, \`file_name\` varchar(255) NOT NULL, \`file_path\` varchar(255) NOT NULL, \`mime_type\` varchar(255) NOT NULL, \`file_size\` int NOT NULL, \`uploaded_by\` uuid NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`inventory_items\` (\`id\` uuid NOT NULL, \`tenant_id\` uuid NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`sku\` varchar(255) NOT NULL, \`name\` varchar(255) NOT NULL, \`unit\` varchar(255) NULL, \`quantity_on_hand\` int NOT NULL DEFAULT '0', \`low_stock_threshold\` int NOT NULL DEFAULT '5', \`cost_price\` decimal(12,2) NOT NULL DEFAULT '0.00', \`sell_price\` decimal(12,2) NOT NULL DEFAULT '0.00', \`is_active\` tinyint NOT NULL DEFAULT 1, UNIQUE INDEX \`IDX_506537c242ac456b0121b8b110\` (\`tenant_id\`, \`sku\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ticket_parts\` (\`id\` uuid NOT NULL, \`tenant_id\` uuid NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`ticket_id\` uuid NOT NULL, \`inventory_item_id\` uuid NOT NULL, \`quantity\` int NOT NULL, \`unit_cost_price\` decimal(12,2) NOT NULL, \`unit_sell_price\` decimal(12,2) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`invoices\` (\`id\` uuid NOT NULL, \`tenant_id\` uuid NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`invoice_number\` varchar(255) NOT NULL, \`ticket_id\` uuid NOT NULL, \`customer_id\` uuid NOT NULL, \`parts_amount\` decimal(12,2) NOT NULL DEFAULT '0.00', \`labor_amount\` decimal(12,2) NOT NULL DEFAULT '0.00', \`total_amount\` decimal(12,2) NOT NULL, \`status\` varchar(255) NOT NULL DEFAULT 'unpaid', \`paid_at\` datetime NULL, UNIQUE INDEX \`IDX_2d3ced63b2eb8ae2407b1d3493\` (\`tenant_id\`, \`invoice_number\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`warranties\` (\`id\` uuid NOT NULL, \`tenant_id\` uuid NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`ticket_id\` uuid NOT NULL, \`customer_id\` uuid NOT NULL, \`device_type\` varchar(255) NULL, \`device_model\` varchar(255) NULL, \`warranty_months\` int NOT NULL, \`start_date\` datetime NOT NULL, \`end_date\` datetime NOT NULL, \`status\` varchar(255) NOT NULL DEFAULT 'active', \`notes\` text NULL, UNIQUE INDEX \`IDX_a6cd030965a1e630d7f3e73afe\` (\`tenant_id\`, \`ticket_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`orders\` (\`id\` uuid NOT NULL, \`tenant_id\` uuid NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`order_number\` varchar(255) NOT NULL, \`customer_id\` uuid NOT NULL, \`status\` varchar(255) NOT NULL DEFAULT 'pending', \`total_amount\` decimal(12,2) NOT NULL DEFAULT '0.00', \`notes\` text NULL, UNIQUE INDEX \`IDX_39b6a35bef7fd890df84baacba\` (\`tenant_id\`, \`order_number\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`order_items\` (\`id\` uuid NOT NULL, \`tenant_id\` uuid NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`order_id\` uuid NOT NULL, \`inventory_item_id\` uuid NOT NULL, \`quantity\` int NOT NULL, \`unit_price\` decimal(12,2) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`conversations\` (\`id\` uuid NOT NULL, \`tenant_id\` uuid NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`ticket_id\` uuid NULL, \`customer_id\` uuid NOT NULL, \`customer_language\` varchar(255) NOT NULL, \`staff_language\` varchar(255) NOT NULL DEFAULT 'vi', \`auto_translate_enabled\` tinyint NOT NULL DEFAULT 0, \`channel\` varchar(255) NOT NULL DEFAULT 'internal', \`external_contact_id\` varchar(255) NULL, \`status\` varchar(255) NOT NULL DEFAULT 'open', \`assigned_staff_id\` uuid NULL, \`queue_number\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`chat_messages\` (\`id\` uuid NOT NULL, \`tenant_id\` uuid NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`conversation_id\` uuid NOT NULL, \`sender_type\` varchar(255) NOT NULL, \`original_text\` text NOT NULL, \`original_language\` varchar(255) NOT NULL, \`translated_text\` text NOT NULL, \`translated_language\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`price_catalog\` (\`id\` uuid NOT NULL, \`tenant_id\` uuid NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`skill_code\` varchar(255) NOT NULL, \`description\` varchar(255) NOT NULL, \`labor_price\` decimal(12,2) NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, UNIQUE INDEX \`IDX_25b00a4e8bdbe033a65453c950\` (\`tenant_id\`, \`skill_code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`knowledge_entries\` (\`id\` uuid NOT NULL, \`tenant_id\` uuid NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`title\` varchar(255) NOT NULL, \`content\` text NOT NULL, \`category\` varchar(255) NULL, \`tags\` json NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`diagnostic_cache\` (\`id\` uuid NOT NULL, \`tenant_id\` uuid NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`query_hash\` varchar(255) NOT NULL, \`device_type\` varchar(255) NULL, \`issue_description\` text NOT NULL, \`result_json\` json NOT NULL, \`hit_count\` int NOT NULL DEFAULT '0', UNIQUE INDEX \`IDX_df630de734b8a40be87e1e1278\` (\`tenant_id\`, \`query_hash\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`add_on_rules\` (\`id\` uuid NOT NULL, \`tenant_id\` uuid NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`trigger_type\` varchar(255) NOT NULL, \`trigger_value\` varchar(255) NOT NULL, \`suggested_product_skus\` json NULL, \`suggested_service_note\` text NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`telegram_bindings\` (\`id\` uuid NOT NULL, \`tenant_id\` uuid NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`telegram_chat_id\` varchar(255) NOT NULL, \`user_id\` uuid NOT NULL, \`telegram_username\` varchar(255) NULL, \`active_session_id\` uuid NULL, \`active_channel_type\` varchar(255) NULL, \`next_queue_number\` int NOT NULL DEFAULT '1', UNIQUE INDEX \`IDX_e85655583123fa3d705681726a\` (\`tenant_id\`, \`telegram_chat_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`web_chat_sessions\` (\`id\` uuid NOT NULL, \`tenant_id\` uuid NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`customer_id\` uuid NULL, \`created_ticket_id\` uuid NULL, \`control_mode\` varchar(255) NOT NULL DEFAULT 'ai', \`assigned_staff_id\` uuid NULL, \`queue_number\` int NULL, \`customer_language\` varchar(255) NOT NULL DEFAULT 'en', \`auto_translate_enabled\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`web_chat_messages\` (\`id\` uuid NOT NULL, \`tenant_id\` uuid NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`session_id\` uuid NOT NULL, \`role\` varchar(255) NOT NULL, \`text\` text NOT NULL, \`image_path\` varchar(255) NULL, \`image_mime_type\` varchar(255) NULL, \`staff_id\` uuid NULL, \`translated_text\` text NULL, \`translated_language\` varchar(255) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`event_log\` (\`id\` uuid NOT NULL, \`tenant_id\` uuid NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`event_type\` varchar(255) NOT NULL, \`payload\` json NOT NULL, \`status\` varchar(255) NOT NULL DEFAULT 'pending', \`published_at\` datetime NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE \`event_log\``);
        await queryRunner.query(`DROP TABLE \`web_chat_messages\``);
        await queryRunner.query(`DROP TABLE \`web_chat_sessions\``);
        await queryRunner.query(`DROP INDEX \`IDX_e85655583123fa3d705681726a\` ON \`telegram_bindings\``);
        await queryRunner.query(`DROP TABLE \`telegram_bindings\``);
        await queryRunner.query(`DROP TABLE \`add_on_rules\``);
        await queryRunner.query(`DROP INDEX \`IDX_df630de734b8a40be87e1e1278\` ON \`diagnostic_cache\``);
        await queryRunner.query(`DROP TABLE \`diagnostic_cache\``);
        await queryRunner.query(`DROP TABLE \`knowledge_entries\``);
        await queryRunner.query(`DROP INDEX \`IDX_25b00a4e8bdbe033a65453c950\` ON \`price_catalog\``);
        await queryRunner.query(`DROP TABLE \`price_catalog\``);
        await queryRunner.query(`DROP TABLE \`chat_messages\``);
        await queryRunner.query(`DROP TABLE \`conversations\``);
        await queryRunner.query(`DROP TABLE \`order_items\``);
        await queryRunner.query(`DROP INDEX \`IDX_39b6a35bef7fd890df84baacba\` ON \`orders\``);
        await queryRunner.query(`DROP TABLE \`orders\``);
        await queryRunner.query(`DROP INDEX \`IDX_a6cd030965a1e630d7f3e73afe\` ON \`warranties\``);
        await queryRunner.query(`DROP TABLE \`warranties\``);
        await queryRunner.query(`DROP INDEX \`IDX_2d3ced63b2eb8ae2407b1d3493\` ON \`invoices\``);
        await queryRunner.query(`DROP TABLE \`invoices\``);
        await queryRunner.query(`DROP TABLE \`ticket_parts\``);
        await queryRunner.query(`DROP INDEX \`IDX_506537c242ac456b0121b8b110\` ON \`inventory_items\``);
        await queryRunner.query(`DROP TABLE \`inventory_items\``);
        await queryRunner.query(`DROP TABLE \`ticket_attachments\``);
        await queryRunner.query(`DROP TABLE \`ticket_status_history\``);
        await queryRunner.query(`DROP INDEX \`IDX_d83f5fcb42383c9feea08bbe1f\` ON \`tickets\``);
        await queryRunner.query(`DROP TABLE \`tickets\``);
        await queryRunner.query(`DROP INDEX \`IDX_d9ef0802e47c0384f5831b5973\` ON \`customers\``);
        await queryRunner.query(`DROP TABLE \`customers\``);
        await queryRunner.query(`DROP INDEX \`IDX_e9f4c2efab52114c4e99e28efb\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_3021c18db2b363ae9324c826c5\` ON \`tenants\``);
        await queryRunner.query(`DROP TABLE \`tenants\``);
    }

}
