version: '3.8'

services:
  mariadb:
    image: mariadb:11
    container_name: ai-bos-mariadb
    environment:
      MARIADB_USER: ai_bos
      MARIADB_PASSWORD: ai_bos_password
      MARIADB_DATABASE: ai_bos
      MARIADB_ROOT_PASSWORD: root_password_doi_truoc_khi_dung_that
    ports:
      - '3306:3306'
    volumes:
      - ai_bos_db_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: ai-bos-redis
    ports:
      - '6379:6379'

volumes:
  ai_bos_db_data:
